version: '3.1'

services:
  db_note:
    image: postgres:12
    restart: always
    ports:
      - "5423:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
